/* ================================================================== *
 * str_enc_generated.h - Auto-generated. DO NOT EDIT.                  *
 *                                                                    *
 * Regenerated by scripts/gen_str_enc.ps1 from scripts/strings.list.  *
 * Runtime XOR decrypt lives in shared/str_enc.c.                     *
 * ================================================================== */
#ifndef SVCLDB_STR_ENC_GENERATED_H
#define SVCLDB_STR_ENC_GENERATED_H

#include <stddef.h>

#define SVC_STR_KEY_MIX  0x5Au

typedef enum {
    SVC_STR_PRODUCT_NAME = 0,
    SVC_STR_INSTALL_DIR_LEAKY = 1,
    SVC_STR_SVCLDB_TOKEN = 2,
    SVC_STR_SVCLDB_API_KEY = 3,
    SVC_STR_SHUTDOWN_EVENT = 4,
    SVC_STR_PAYLOAD_INIT = 5,
    SVC_STR_PAYLOAD_READY = 6,
    SVC_STR_HOOKS_INSTALLED = 7,
    SVC_STR_HOOKS_UNINSTALLED = 8,
    SVC_STR_HANDSHAKE_OK = 9,
    SVC_STR_HANDSHAKE_BAD_HEADER = 10,
    SVC_STR_HANDSHAKE_TOKEN_INVALID = 11,
    SVC_STR_CONFIG_UNAVAIL = 12,
    SVC_STR_PEB_UNLINKED = 13,
    SVC_STR_PE_WIPED = 14,
    SVC_STR_HOOK_PRESENT = 15,
    SVC_STR_HOOK_DDPRESENT = 16,
    SVC_STR_HOOK_LEGACY_PRESENT = 17,
    SVC_STR_HOOK_RC_WINDOW = 18,
    SVC_STR_HOOK_RC_VISUAL = 19,
    SVC_STR_HOOK_RC_WINDOW_FAIL = 20,
    SVC_STR_HOOK_RC_VISUAL_FAIL = 21,
    SVC_STR_HOOK_PN_DD = 22,
    SVC_STR_HOOK_PN_LEGACY = 23,
    SVC_STR_AUTH_HEADER_FMT = 24,
    SVC_STR_ANTHROPIC_VERSION = 25,
    SVC_STR_OPENAI_CHAT_URL = 26,
    SVC_STR_ANTHROPIC_MSG_URL = 27,
    SVC_STR_GOOGLE_GEN_URL = 28,
    SVC_STR_OPENROUTER_URL = 29,
    SVC_STR_MODEL_GEMINI_FLASH_LITE = 30,
    SVC_STR_MODEL_GEMINI_PRO = 31,
    SVC_STR_MODEL_GEMINI_3_PRO = 32,
    SVC_STR_MODEL_GEMINI_3_FLASH = 33,
    SVC_STR_MODEL_OPENAI_GPT55 = 34,
    SVC_STR_MODEL_ANTHROPIC_OPUS = 35,
    SVC_STR_PDB_CVISUAL_RC = 36,
    SVC_STR_PDB_CWNODE_RC = 37,
    SVC_STR_ERR_INVALID_KEY_HINT = 38,
    SVC_STR_ERR_RATE_LIMIT = 39,
    SVC_STR_ERR_MODEL_UNAVAIL = 40,
    SVC_STR_NO_QUESTION = 41,
    SVC_STR_SUBCHK_THREAD_UP = 42,
    SVC_STR_SUBCHK_SELF_UNLOAD = 43,
    SVC_STR_SUBCHK_INACTIVE = 44,
    SVC_STR_SUBCHK_NET_FAIL = 45,
    SVC_STR_RIN_CLASS = 46,
    SVC_STR_RIN_REGISTERED = 47,
    SVC_STR_COUNT
} svc_str_id_t;

/* Writable so svc_str_init() can XOR in place. Read-only after init. */
extern char g_svc_enc_blob[1673];

typedef struct { size_t offset; size_t length; } svc_str_entry_t;
extern const svc_str_entry_t g_svc_enc_table[SVC_STR_COUNT];

#endif /* SVCLDB_STR_ENC_GENERATED_H */
