# =================================================================
#  gen_str_enc.ps1 - Generate shared/str_enc_generated.h
#
#  Reads scripts/strings.list and produces the encrypted blob + table
#  that shared/str_enc.c walks at runtime.
#
#  Encryption: per-byte XOR with a per-index key derived from the
#  byte's position in the string + the string's length. Matches
#  _svc_key_byte() in shared/str_enc.c exactly.
#
#  Regenerate whenever strings.list changes:
#      powershell -File scripts/gen_str_enc.ps1
# =================================================================

$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$listPath   = Join-Path $repoRoot 'scripts\strings.list'
$outPath    = Join-Path $repoRoot 'shared\str_enc_generated.h'

if (!(Test-Path $listPath)) { Write-Error "missing strings.list: $listPath"; exit 1 }

# --- Choose a KEY_MIX byte. Fixed at codegen time so re-runs produce
#     identical output; matches C-side _svc_key_byte(). Change ONLY if
#     you also change shared/str_enc.c's SVC_STR_KEY_MIX reference.
$keyMix = 0x5A

function KeyByte([int]$idx, [int]$len) {
  return ((($idx * 37) + ($len * 91) + $keyMix) -band 0xFF)
}

# --- Parse strings.list ---
$entries = @()
foreach ($line in Get-Content -LiteralPath $listPath) {
  $t = $line.Trim()
  if (!$t -or $t.StartsWith('#')) { continue }
  $eq = $t.IndexOf('|')
  if ($eq -lt 0) { Write-Warning "skip malformed line: $t"; continue }
  $name = $t.Substring(0, $eq).Trim()
  $val  = $t.Substring($eq + 1)   # do NOT trim; preserve trailing spaces
  if (!$name) { continue }
  $entries += [pscustomobject]@{ Name = $name; Value = $val }
}
Write-Host "Loaded $($entries.Count) strings from strings.list"

# --- Build the encrypted blob + offset/length table ---
$blob  = New-Object System.Collections.Generic.List[byte]
$table = @()
foreach ($e in $entries) {
  $bytes = [System.Text.Encoding]::UTF8.GetBytes($e.Value)
  $len   = $bytes.Length
  $offset = $blob.Count
  for ($i = 0; $i -lt $len; $i++) {
    $enc = ($bytes[$i] -bxor (KeyByte $i $len)) -band 0xFF
    $blob.Add([byte]$enc) | Out-Null
  }
  # NUL terminator so the decrypted string is a valid C string. The
  # NUL itself is NOT XOR'd (it's outside [offset, offset+length)).
  $blob.Add([byte]0) | Out-Null
  $table += [pscustomobject]@{ Name = $e.Name; Offset = $offset; Length = $len }
}
Write-Host "Encrypted blob: $($blob.Count) bytes total"

# --- Emit the header ---
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* ================================================================== *')
[void]$sb.AppendLine(' * str_enc_generated.h - Auto-generated. DO NOT EDIT.                  *')
[void]$sb.AppendLine(' *                                                                    *')
[void]$sb.AppendLine(' * Regenerated by scripts/gen_str_enc.ps1 from scripts/strings.list.  *')
[void]$sb.AppendLine(' * Runtime XOR decrypt lives in shared/str_enc.c.                     *')
[void]$sb.AppendLine(' * ================================================================== */')
[void]$sb.AppendLine('#ifndef SVCLDB_STR_ENC_GENERATED_H')
[void]$sb.AppendLine('#define SVCLDB_STR_ENC_GENERATED_H')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include <stddef.h>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("#define SVC_STR_KEY_MIX  0x$('{0:X2}' -f $keyMix)u")
[void]$sb.AppendLine('')

# Enum
[void]$sb.AppendLine('typedef enum {')
for ($i = 0; $i -lt $table.Count; $i++) {
  [void]$sb.AppendLine("    SVC_STR_$($table[$i].Name) = $i,")
}
[void]$sb.AppendLine("    SVC_STR_COUNT")
[void]$sb.AppendLine('} svc_str_id_t;')
[void]$sb.AppendLine('')

# Blob (writable — we XOR in place at init)
[void]$sb.AppendLine('/* Writable so svc_str_init() can XOR in place. Read-only after init. */')
[void]$sb.AppendLine("extern char g_svc_enc_blob[$($blob.Count)];")
[void]$sb.AppendLine('')

# Offset/length table
[void]$sb.AppendLine('typedef struct { size_t offset; size_t length; } svc_str_entry_t;')
[void]$sb.AppendLine("extern const svc_str_entry_t g_svc_enc_table[SVC_STR_COUNT];")
[void]$sb.AppendLine('')

[void]$sb.AppendLine('#endif /* SVCLDB_STR_ENC_GENERATED_H */')

# --- Emit companion .c-side definitions ---
# Because g_svc_enc_blob[] must be writable (we XOR in place), it needs a
# .c-level definition rather than living in the header. Put it in the
# same generated file as an included-once translation unit.
# We inline it via a second header that str_enc.c includes.

$dataPath = Join-Path $repoRoot 'shared\str_enc_generated_data.h'
$sbData = New-Object System.Text.StringBuilder
[void]$sbData.AppendLine('/* Auto-generated data. Included ONCE from shared/str_enc.c only. */')
[void]$sbData.AppendLine('#include "str_enc_generated.h"')
[void]$sbData.AppendLine('')

# blob definition
[void]$sbData.Append('char g_svc_enc_blob[' + $blob.Count + '] = {')
for ($i = 0; $i -lt $blob.Count; $i++) {
  if (($i % 16) -eq 0) { [void]$sbData.AppendLine(); [void]$sbData.Append('    ') }
  [void]$sbData.Append("0x$('{0:X2}' -f $blob[$i]),")
}
[void]$sbData.AppendLine('')
[void]$sbData.AppendLine('};')
[void]$sbData.AppendLine('')

# table definition
[void]$sbData.AppendLine('const svc_str_entry_t g_svc_enc_table[SVC_STR_COUNT] = {')
foreach ($e in $table) {
  [void]$sbData.AppendLine("    { $($e.Offset), $($e.Length) },")
}
[void]$sbData.AppendLine('};')

# --- Write both files ---
Set-Content -LiteralPath $outPath  -Value $sb.ToString()     -Encoding utf8 -NoNewline
Set-Content -LiteralPath $dataPath -Value $sbData.ToString() -Encoding utf8 -NoNewline
Write-Host "Wrote $outPath"
Write-Host "Wrote $dataPath"
Write-Host ""
Write-Host "Encrypted $($table.Count) strings, blob total $($blob.Count) bytes."
